version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
      
  python:
    build: ./
    depends_on:
      - db
      - redis
    restart: always

