# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    environment: app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Test with unittest
      id: tests
      run: |
        export BOT_TOKEN=${{ secrets.BOT_TOKEN }} |
        export DB_CONNECT_LINK=${{ secrets.DB_CONNECT_LINK }} |
        export REDIS_HOST=${{ secrets.REDIS_HOST }} |
        python -m unittest tests
      continue-on-error: true
    - name: Rollback
      if: ${{ steps.tests.outcome == 'failure' }}
      run: |
        git config --global user.name "B. Terskow"
        git config --global user.email "tersk.bo@gmail"
        git reset --hard HEAD~1
        git push origin master --force
